server:
  port: 8080  #启动其他实例时需要修改端口号
spring:
  application:
    name: service-producer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/,http://localhost:8889/eureka/,http://localhost:8890/eureka/