server:
  port: 8890
spring:
  application:
    name: eureka-server-center
#  security:
#    basic:
#      enable:true
#    user:
#      name: root
#      password: 842234092
eureka:
  instance:
    hostname: eureka-server-3
  client:
    service-url:
      defaultZone: http://eureka-server:8888/eureka/,http://eureka-server-2:8889/eureka/
#  server:
#    enable-self-preservation: false